"use client"
import * as React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "../public/styles/global.scss";
import { NextUIProvider } from "@nextui-org/react";
// import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokédex with NextJS and NextUI",
  description: "Generated by Edgar Eduardo Torres Hernández",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Pokédex</title>
      </head>
      <body className={inter.className}>
        {" "}
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
